#!/bin/bash

a=$1
b=$2

if [ $a -eq $b ]
then
	echo "$a -eq $b: a is equal b"
else
	echo "$a -eq $b: a is not equal b"
fi

if [ $a -ne $b ]
then
	echo "$a -ne $b: a is not equal to b"
else
	echo "$a -ne $b: a is equal to b"
fi

if [ $a -gt $b ]
then
	echo "$a -qt $b: a is greater than b"
else
	echo "$a -qt $b: a is not greater than b"
fi

if [ $a -lt $b ]
then
	echo "$a -lt $b: a is less than b"
else
	echo "$a -lt $b: a is not less than b"
fi

if [ $a -ge $b ]
then
	echo "$a -qe $b:a is greater than b"
else
	echo "$a -qe $b: a is not greater than b"
fi

if [ $a -le $b ]
then
	echo "$a -le $b: a is less or equal to b"
else
	echo "$a -le $b: a is not less or equal than b"
fi
